name: Override environment variables
on: push
env:
  EXAMPLE: Defined by workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{env.EXAMPLE}}"
      - env:
          EXAMPLE: OK
        run: echo "${{env.EXAMPLE}}"
